### ISSUE TITLE
Update Readme on Node V8

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/nota#105]
### Problem

The Readme needs to reflect that the node environment is now version 8

### Solution

Add information regarding setup that reflects the use of node v8.

**Comment by osmarpetry** [comment]
@jaylenw  I do not understand, you want to change only one line where says the version of Node?

**Comment by jaylenw** [comment]
Hello @osmarpetry , thank you for being interested in contributing. We just need to replace the node version with 8. I have left a comment on this PR here explaining more in detail #106 .

**Comment by osmarpetry** [comment]
@jaylenw thanks for your attention, the PR is there: https://github.com/jaylenw/nota/pull/107
