### ISSUE TITLE
Change CI / CD

### ISSUE THREAD

**Issue by jaylenw** [jaylenw/nota#61]
### Problem
* Travis is using ubuntu 14.04 while our local dev environment is 16.04. This makes it more difficult to make sure packages and commands are working as expected between the two

* Travis will not add 16.04 support. Recommend way is to use docker containers

* Implement new CI  by using docker images and CD by implementing docker containers running on production for Nota

### Solution

Implement local setup of docker images/containers and put them to a registry.

Have CI pull the containers for test.

Setup process to where merging code to different branches will push a new deployment to a different environment.

**Comment by jdbohrman** [comment]
I can help with this as well if you'd like.

**Comment by jdbohrman** [comment]
https://circleci.com/docs/2.0/custom-images/

https://github.com/circleci-public/dockerfile-wizard

**Comment by jaylenw** [comment]
Hi @jdbohrman , thank you for being interested in helping out. I would love to have your assistance!

I plan on putting more thought in a plan to resolve this issue and know it will be a multi-step process in getting everything I imagined done. I will update the description of this issue when I can iron out more details.

Thank you for providing those links. I will look into them.

In the meantime, are you able to get your local development setup for the back-end? Here is a vagrant file that will allow you to quickly get setup with the tools to begin work on the project. https://github.com/jaylenw/VagrantBoxes/tree/master/Nota. Once you are able to run all unit tests in the test environment local (as described in readme) we can continue on how we may solve this issue. Please let me know if you have any questions.

Thanks again.

**Comment by jaylenw** [comment]
Hello @jdbohrman ,

Awesome! I am glad you are able to get the unit tests running. No problem, I know for myself it's difficult to squeeze free time to work on this :).

Here is what I think we should do in getting this issue resolved. Let me know any feedback or questions you may have.

Let's install docker and docker compose in our vagrant machine to the latest version that supports Ubuntu 16.04.

**Step 1:**

Because we are already able to run tests in our environment and would like to implement docker into our CI/CD process, let's first work on getting a docker image built just for Nota.

This image will be based off of Ubuntu 16.04 and will only have the dependencies installed just to get Nota running. For testing purposes for now, let's get this image built and it will use the mongodb database on the host. We may have to change some settings to allow mongodb to listen to requests outside `localhost`, and document this if this is the case. Once we are able to get our Nota docker image built inside our vagrantbox, we can run the image as a container and run the script inside of it to run the unit tests. If everything is working fine there we can move along to the next step.

**Step 2:** 

This involves making a Nota service with docker. We would use docker compose to make a service that will have the backend code of Nota and our mongodb in separate docker images. First, we would need to build our mongodb image and then create a `docker-compose.yml` describing the Nota service. Once that is done, move forward and run the Nota service with docker compose and the test script to run the unit tests to make sure everything is running properly.

**Step 3:**

I will go ahead and push the two images to docker hub and we can check in our docker-compose file to the `master` branch of this repo. We will then modify the `.travis.yml` file to use the docker-compose.yml file for running the tests in travis-ci.

**Step 4:**

This involves us making modifications to our existing docker configuration if needed to support running Nota in develop, stage, and production on our cloud server.

Further details for this step will come later. For now, thinking of having Portainer and Watchtower manager our new and existing container instances for those deployments.

Useful Links:

https://docs.docker.com/get-started/
https://portainer.io/index.html
https://docs.travis-ci.com/user/docker/
https://github.com/v2tec/watchtower

-----

So James, let's focus on creating a docker image of Nota first as described in step 1. You can upload your docker file for the image to this issue or create a branch with the docker file in it. I will try and work on this too and update you on any info as well.

Thank you.

**Comment by jaylenw** [comment]
We should also record whatever dependencies we need to install so that we can update the README.md and vagrantbox https://github.com/jaylenw/VagrantBoxes/tree/master/Nota

**Comment by jdbohrman** [comment]
> We should also record whatever dependencies we need to install so that we can update the README.md and vagrantbox https://github.com/jaylenw/VagrantBoxes/tree/master/Nota

Ok, I'm back now. Busy week lol. I'm going to work on this when I get off in just a bit.

**Comment by jaylenw** [comment]
Hey @jdbohrman , took me longer than expected to get this done but docker-compose has not been setup and unit tests are running fine. Merged https://github.com/jaylenw/nota/pull/69

**Comment by jaylenw** [comment]
Everything looks like it is working properly so far as of the merge of #125  and #126 . Closing this issue.
